### ISSUE TITLE
github.com:rescript-lang/ninja.git clone failing on install

### ISSUE THREAD

**Issue by danwetherald** [believer/coc-rescript#1]
When trying to install I am getting an error when tying to clone the ninja repo. 

git@github.com: Permission denied (publickey)

fatal: clone of 'git@github.com:rescript-lang/ninja.git'

**Comment by believer** [comment]
I've moved `bs-platform` to `devDependencies` so it doesn't get installed with the plugin, that should hopefully help. It's released as `1.3.2`, please test it and tell me if it solved the issue.

**Comment by danwetherald** [comment]
Ah! We are in business, I now am able to successfully install, but still no auto format on save :/

Any ideas?

**Comment by believer** [comment]
Perfect! Did you add this `"coc.preferences.formatOnSaveFiletypes": ["rescript"]` to `:CocConfig`? It's needed to make coc send the formatting event to the language server.

**Comment by danwetherald** [comment]
Yes, that is included in my array of filetypes:

```
"coc.preferences.formatOnSaveFiletypes": [
    "yaml",
    "typescript",
    "javascript",
    "javascript.jsx",
    "typescript.tsx",
    "typescriptreact",
    "javascriptreact",
    "reason",
    "rescript",
    "ruby",
    "graphql",
    "go"
  ],
```

**Comment by believer** [comment]
Great! Are your rescript files using the rescript filetype? I'm using [vim-rescript](https://github.com/amiralies/vim-rescript/) for syntax highlighting, maybe that would make the difference?

**Comment by danwetherald** [comment]
Yup, I also have that installed for syntax highlighting, I have also echoed the filetype and it prints "rescript".

**Comment by believer** [comment]
For some reason, the extension doesn't seem to activate. I'm looking into it.

**Comment by believer** [comment]
Alright, `bs-platform` is of course needed due to imports, e.g. `Belt`. That might resurface the original issue, which I don't really know how to solve. 😅  Seems like it might be something local to your environment?

In order to get formatting to work, you'll also need `bs-platform` >= `8.2.0`.

**Comment by danwetherald** [comment]
Okay, well 1.3.3 is now installing... I did yarn global install bs-platform 8.3.

![image](https://user-images.githubusercontent.com/1211542/95114384-7725d400-0709-11eb-9b32-a2ae0b9ba956.png)

But still nothing, nothing auto formats on save.

**Comment by believer** [comment]
And you have `bs-platform` >= 8.2.0 installed in your project?

Can you see any events in `:CocCommand` -> `workspace.showOutput` -> `rescript`? There should be a formatting message there or maybe an error?

**Comment by danwetherald** [comment]
In the project I have `"bs-platform": "^8.3.0"` under devDependencies yes.

Looks like rescript is not showing as a channel:

![image](https://user-images.githubusercontent.com/1211542/95115005-6aee4680-070a-11eb-891c-ffc150a99b7f.png)

**Comment by believer** [comment]
OK! I found the error, I had accidentally removed `bs-` from the path to `bs-platform` when refactoring with `bs-platform@8.3.0` 😞

Hopefully `1.3.4` will work for you too @dan003400

**Comment by danwetherald** [comment]
BOOM 🎉

We are in business. So for others who experience this in the future, we need to make sure we have `bs-platform >= 8.3` installed globally on your machine? Was this the fix?

Thanks!

**Comment by believer** [comment]
Awesome! It shouldn't be needed, I don't have it installed globally. I don't really know why the initial error happened, but it seems like something with either Git or ReScript since I only install `bs-platform`. But it did surface other issues which was great. 😄

Thank you very much for taking the time to test! 💯
