### ISSUE TITLE
How to get error highlighting/diagnostics working?

### ISSUE THREAD

**Issue by chrischen** [believer/coc-rescript#2]
I've updated to bs-platform 8.3.0, but there's no error diagnostics or highlighting on syntax errors. Is this supported yet? Re-formatting works.

Using neovim and vimR gui on macos.

**Comment by believer** [comment]
Do you get a file called `lib/bs/.compiler.log` when you run `bsb -make-world`? That's the file it's parsing to display the errors.

![Screenshot 2020-10-06 at 12 57 01](https://user-images.githubusercontent.com/1478102/95193115-938e4300-07d3-11eb-8310-554fb87e0a3b.png)

**Comment by chrischen** [comment]
Yes that file exists and has the error

```
#Start(1601982230498)

  Syntax error!
  /Users/Chris/.../src/.../Types.res:171:5-8
  
  169 ┆ 
  170 ┆ module Question = 
  171 ┆   type t = Question(string)
  172 ┆   type error<'a> = [> #QuestionTooShortError(int) | #QuestionMissingQ
        uestionMarkError] as 'a
  173 ┆ 
  
  `type` is a reserved keyword. Keywords need to be escaped: \"type"

#Done(1601982230509)
```

**Comment by believer** [comment]
Good good! Can you see any errors in `:CocOpenLog` or `:CocCommand -> workspace.showOutput -> rescript`?

**Comment by chrischen** [comment]
Hi,

I see this at the top of the workspace.showOutput

```
/Users/Chris/.config/coc/extensions/node_modules/coc-rescript/node_modules/bs-platform/lib/js/belt_Array.js:239
  var result = new Array(len);
               ^

RangeError: Invalid array length
...
...
at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:146:12)

```

**Comment by believer** [comment]
Perfect, that's something to go on! I'll take a look at it in a bit

**Comment by believer** [comment]
I've tested it in VimR and it seems to be an issue with VimR setting the current working directory to the root folder, this way the watcher can't find the `.compiler.log`.

I added `vimr` to my PATH using the "Copy 'vimr' CLI Tool" in the preferences and opened a ReScript project from the terminal. This way the current working directory is set to the project and the `.compiler.log` can be found. That's the best way I could find right now 😄 

You can also scope down using the explorer in VimR, but then you have to restart the plugin afterwards. `:CocList -> extensions -> press enter on coc-rescript to deactivate -> press enter on coc-rescript to activate` 

Tested with `coc-rescript@1.3.4`.

**Comment by chrischen** [comment]
Hmm I'm not sure this is the same issue causing my problem then? I tried using terminal neovim and still no diagnostics.

For both nvim and vimr I run the command in the project root (where the bsconfig.json file is) to open neovim, and then I open the .res file it is not showing any error diagnostics.

The coc-reason plugin is working as .re files show diagnostics.

 Also now CocCommand -> workspace.showOutput -> rescript is blank (empty).

**Comment by believer** [comment]
You'll need to save once to display the errors, it's not checking on load yet. You also need to have the compiler running (`bsb -make-world -w`) or run it once (`bsb -make-world`) to update the `.compiler.log` after opening the file.

`workspace.showOutput` is blank because I'm not logging anything at the moment, I've readded the `message` in `1.3.5` for debugging.

**Comment by chrischen** [comment]
Hi,

Yes i have bsb -make-world -w running and saved the file.

Auto formatting works but no diagnostics in either vimr or terminal neovim.

.compiler.log exists and has the current error shown in the bsb compiler output.

Thanks!
Chris
Creative Consultant
________________________________

**Comment by believer** [comment]
I added handling for the error in https://github.com/believer/coc-rescript/issues/2#issuecomment-704202107 in `1.3.6`, other than that I don't really know what's going on 😅
